server:
  port: 8081

spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  application:
    name: api-passenger
  redis:
    host: 120.26.4.95
    port: 6379
    database: 0